# Site settings
title: Archeflu
email: antoine.jullien@gmail.com
description: Java & Agilité
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  a-jullien
paginate: 5

# Build settings
markdown: kramdown
highlighter: pygments
