# Site settings
title: Archeflu
email: antoine.jullien@gmail.com
description: Java & Agilité
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  a-jullien
paginate: 5

# Build settings
markdown: kramdown
highlighter: pygments

image:
  source: assets/images/_fullsize
  output: generated
  presets:
    # Proportional preset
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 350
    # Scaled and cropped preset
    half:
      width: 400
      height: 400